### ISSUE TITLE
🐞[Bug] Error running FileMonitor

### ISSUE THREAD

**Issue by nothing2obvi** [David-Maisonave/Axter-Stash#5]
### Please enter steps to reproduce the behavior.

1. Changed only a time for a task in `filemonitor_config.py` (so I could test out FileMonitor) from `05:30` to `14:30`. That's the only thing I changed.
2. Reload plugins
3. When it is that time, get error in logs

### Stash Version (from Settings -> About)

v0.27.2

### What Operating System (OS)?

OrbStack on MacOS Sequoia 15.1.1

### Phone or tablets

N/A

### What browser and version?

Opera version: 114.0.5282.235

### Expected Behavior

The plugin runs.

### Logging

[Plugin / FileMonitor] WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv 
[Plugin / FileMonitor] Traceback (most recent call last): 
[Plugin / FileMonitor]   File "/root/.stash/plugins/FileMonitor/filemonitor.py", line 18, in <module> 
[Plugin / FileMonitor]     from filemonitor_config import config 
[Plugin / FileMonitor]   File "/root/.stash/plugins/FileMonitor/filemonitor_config.py", line 37 
[Plugin / FileMonitor]     "weekday" : "saturday",  "time" : "02:30"}, # [Plugin Tasks] -> DupFileManager -> [Delete Tagged Duplicates] 6 days after tagging at 2:30AM 
[Plugin / FileMonitor]                                              ^ 
[Plugin / FileMonitor] SyntaxError: closing parenthesis '}' does not match opening parenthesis '[' on line 13 
runPluginOperation: input: runPluginOperation exit status 1 
```

### Snapshot(s)

_No response_

### Additional context

_No response_

**Comment by nothing2obvi** [comment]
Yeah I can't even get it to run now. I'll have to play around with it more later.

**Comment by nothing2obvi** [comment]
Okay actually, I had it running for a while and then got this:

```
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor] StdErr: [LN:918] ERR: Exception while running FileMonitor. runType='CommandLineStartLibMonitor'; Error: [Errno 2] No such file or directory 
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor] TraceBack=Traceback (most recent call last): 
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor]   File "/root/.stash/plugins/FileMonitor/filemonitor.py", line 912, in <module> 
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor]     start_library_monitor() 
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor]   File "/root/.stash/plugins/FileMonitor/filemonitor.py", line 616, in start_library_monitor 
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor]     observer.start()  
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor]   File "/usr/lib/python3.12/site-packages/watchdog/observers/api.py", line 264, in start 
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor]     emitter.start()   
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor]   File "/usr/lib/python3.12/site-packages/watchdog/utils/__init__.py", line 75, in start 
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor]     self.on_thread_start() 
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor]   File "/usr/lib/python3.12/site-packages/watchdog/observers/inotify.py", line 119, in on_thread_start 
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor]     self._inotify = InotifyBuffer(path, recursive=self.watch.is_recursive, event_mask=event_mask) 
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor]   File "/usr/lib/python3.12/site-packages/watchdog/observers/inotify_buffer.py", line 30, in __init__ 
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor]     self._inotify = Inotify(path, recursive=recursive, event_mask=event_mask) 
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor]   File "/usr/lib/python3.12/site-packages/watchdog/observers/inotify_c.py", line 187, in __init__ 
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor]     self._add_watch(path, event_mask) 
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor]   File "/usr/lib/python3.12/site-packages/watchdog/observers/inotify_c.py", line 424, in _add_watch 
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor]     Inotify._raise_error() 
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor]   File "/usr/lib/python3.12/site-packages/watchdog/observers/inotify_c.py", line 441, in _raise_error 
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor]     raise OSError(err, os.strerror(err)) 
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor] FileNotFoundError: [Errno 2] No such file or directory 
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor] /usr/lib/python3.12/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown 
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor]   warnings.warn('resource_tracker: There appear to be %d ' 
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor] /usr/lib/python3.12/multiprocessing/resource_tracker.py:267: UserWarning: resource_tracker: '/DavidMaisonaveAxter_FileMonitor': [Errno 2] No such file or directory: '/DavidMaisonaveAxter_FileMonitor' 
ERRO[2024-12-04 18:08:01] [Plugin / FileMonitor]   warnings.warn('resource_tracker: %r: %s' % (name, e)) 
```

**Comment by nothing2obvi** [comment]
Nevermind, I'll open a new issue.
